[project]
name = "airpen"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "aim>=3.29.1",
    "einops>=0.8.1",
    "hydra-core>=1.3.2",
    "matplotlib>=3.10.7",
    "numpy>=2.2.6",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
